celestial_texture = "resources/celestial.png"

[geometry_type.EuclideanSpherical]

[[objects]]

[objects.Disc]
inner_radius = 3.0
outer_radius = 5.0
texture = "resources/disk.png"

[[objects]]

[objects.Sphere]
radius = 2.0
texture = "resources/sphere.png"
position = [0.0, 0.0, 0.0]
