celestial_texture = "resources/celestial.png"
color_normalization = "NoNormalization"

[geometry_type.EuclideanSpherical]

[[objects]]

[objects.Disc]
inner_radius = 3.0
outer_radius = 5.0

[objects.Disc.texture.Bitmap]
path = "resources/disk.png"

[[objects]]

[objects.Sphere]
radius = 2.0
position = [0.0, 0.0, 0.0]

[objects.Sphere.texture.Bitmap]
path = "resources/sphere.png"
