celestial_texture = "resources/celestial.png"

[geometry_type.Euclidean]

[[objects]]

[objects.Disc]
inner_radius = 3.0
outer_radius = 5.0

[objects.Disc.texture.Bitmap]
path = "resources/disk.png"


[[objects]]

[objects.Sphere]
radius = 3.0
position = [0.0, 0.0, 0.0]

[objects.Sphere.texture.Bitmap]
path = "resources/sphere.png"
