color_normalization = "NoNormalization"
celestial_temperature = 0.0

[celestial_texture.Bitmap]
beaming_exponent = 3.0
path = "resources/celestial.png"
#path = "resources/black.png"
#path = "resources/white.png"
color_normalization = "NoNormalization"

[geometry_type.Schwarzschild]
radius = 1.0
horizon_epsilon = 1e-4

[[objects]]

[objects.VolumetricDisc]
inner_radius = 4.05
outer_radius = 11.0
temperature = 1400.0
num_octaves = 8
max_steps = 50000
step_size = 0.002
thickness = 0.2
density_multiplier = 300.0
brightness_reference_temperature = 900.0
absorption = 0.4
scattering = 0.2
noise_scale = [60.0, 2.0, 30.0]
noise_offset = -0.3
#
#[objects.Disc.texture.Bitmap]
#beaming_exponent = 3.0
#path = "resources/orange.png"
#color_normalization = "NoNormalization"

[objects.VolumetricDisc.texture.BlackBody]
beaming_exponent = 7.0
color_normalization = "EqualLuminance"
#color_normalization = "Chromaticity"

#[[objects]]
#
#[objects.Sphere]
#temperature = 2000.0
#radius = 2.0
#position = [-22.5, 0.0, 1.0]
#
#[objects.Sphere.texture.Bitmap]
#beaming_exponent = 3.0
#path = "resources/orange.png"
#color_normalization = "NoNormalization"
