celestial_temperature = 100.0

[celestial_texture.Bitmap]
beaming_exponent = 3.0
path = "resources/celestial.png"

[geometry_type.Kerr]
radius = 1.0
a=0.499
horizon_epsilon = 1e-4

[[objects]]

[objects.Disc]
inner_radius = 0.795
outer_radius = 15.0
temperature = 2000.0

[objects.Disc.texture.BlackBody]
beaming_exponent = 3.0
