celestial_temperature = 0.0

[celestial_texture.Bitmap]
beaming_exponent = 3.0
path = "resources/celestial.png"

[geometry_type.Schwarzschild]
radius = 1.0
horizon_epsilon = 1e-4

[[objects]]

[objects.Disc]
inner_radius = 3.0
outer_radius = 12.0
temperature = 2600.0

[objects.Disc.texture.BlackBody]
beaming_exponent = 3.0
